#!/bin/bash
# Bash script that archives selected Government of Canada web sites using the WARC ISO format.
DATE=`date +"%Y_%m_%d"`
ROOT=/mnt/DIY/web-archiving/warc
SITES=/mnt/DIY/web-archiving/sites/gc-weekly.csv

cat $SITES | while IFS=, read col1 col2
  do
    cd $ROOT
    mkdir $col2-$DATE
    cd $col2-$DATE
    xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltopdf --use-xserver --dpi 200  --page-size Letter "$col1" $col2-$DATE.pdf
    xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltoimage --use-xserver "$col1" temp.png
    pngcrush temp.png $col2-$DATE.png 
    rm temp.png
    /usr/local/bin/wget -m -p -E -k -K -np --warc-file=$col2-$DATE --no-warc-compression --random-wait "$col1"
    cp $col2-$DATE.warc /mnt/DIY/web-archiving/wayback
    cd /mnt/DIY/web-archiving/warc
    /usr/bin/zip -r $col2-$DATE.zip $col2-$DATE
    rm -rf $col2-$DATE
    echo "S'up Dawg? I archived yo $col2 site: $(date)" >> /var/log/webarchiving.log
done
