#!/bin/bash
# Bash script that archives selected Government of Canada web sites using the WARC ISO format.
DATE=`date +"%Y_%m_%d"`
ROOT=/mnt/DIY/web-archiving/warc
SITES=/mnt/DIY/web-archiving/sites/gc-daily.csv

cat $SITES | while IFS=, read col1 col2
  do
    cd $ROOT
    mkdir $col2-$DATE
    cd $col2-$DATE
    xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltopdf --use-xserver --dpi 200  --page-size Letter "$col1" $col2-$DATE.pdf
    xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltoimage --use-xserver "$col1" temp.png
    pngcrush temp.png $col2-$DATE.png 
    cd ..
    /usr/bin/python /usr/local/bin/bagit.py --processes 4 --contact-name 'Nick Ruest' --contact-email 'ruestn@yorku.ca' --source-organization 'York University' --organization-address '4700 Keele Street Toronto, Ontario M3J 1P3 Canada' --contact-phone '+1 (416)736-2100 x 33235' --external-description 'Government of Canada web archiving: $col1 $col2' $col2-$DATE
    /usr/bin/zip -r $col2-$DATE.zip $col2-$DATE
    rm -rf $col2-$DATE
    echo "S'up Dawg? I archived yo $col2 site: $(date)" >> /extra/logs/webarchiving.log
done
