#!/usr/bin/env bash

import_collection_and_delete_files() {
    local collection_name="$1"
    local file_pattern="$2"
    
    local files=($(shopt -s nullglob dotglob; find /mnt/omega/web-archives/import -iname "$file_pattern"))
    if (( ${#files[@]} )); then
        cd /mnt/omega/web-archives
	for file in "${files[@]}"; do
          wb-manager add "$collection_name" "$file"
	done
	for file in "${files[@]}"; do
	  rm "file"
	done
    fi
}

# Activate Python virtual env.
cd /opt
python3 -m venv pywbenv
source pywbenv/bin/activate

# Import collections and delete related files
import_collection_and_delete_files "academic-calendars" "YORK-ACADEMIC-CALENDARS*warc.gz"
import_collection_and_delete_files "yul" "YORK-LIBRARIES*warc.gz"
import_collection_and_delete_files "yu-crs" "YU-CRS*warc.gz"
import_collection_and_delete_files "yu-magazine" "YU-MAGAZINE*warc.gz"
import_collection_and_delete_files "yfile" "YU-YFILE*warc.gz"
import_collection_and_delete_files "YU-SOCIAL-MEDIA" "YU-SOCIAL-MEDIA*warc.gz"
import_collection_and_delete_files "exhibits" "redmine-3934-c-cave*warc.gz"
