#!/bin/bash
# Bash script that archives selected York University web sites using the WARC ISO format.
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DATE=`date +"%Y_%m_%d"`

cd /mnt/big_data/web-archiving/warcs
mkdir YFILE_$DATE
cd YFILE_$DATE
FILESIZE=`ls -sh YFILE_$DATE | awk '{print $1}'`
MODS="
<mods:mods xmlns='http://www.loc.gov/mods/v3' xmlns:mods='http://www.loc.gov/mods/v3' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <mods:titleInfo>
    <mods:title>YFile - $DATE</mods:title>
  </mods:titleInfo>
  <mods:name type='corporate'>
    <mods:namePart>York University's Communications &amp; Public Affairs</mods:namePart>
    <mods:role>
      <mods:roleTerm authority='marcrelator' type='text'>Creator</mods:roleTerm>
    </mods:role>
  </mods:name>
  <mods:typeOfResource>mixed material</mods:typeOfResource>
  <mods:genre authority='lctgm'>Website</mods:genre>
  <mods:originInfo>
    <mods:dateIssued>$DATE</mods:dateIssued>
    <mods:publisher>York University</mods:publisher>
    <mods:place>
      <mods:placeTerm authority='marccountry' type='code'>Canada</mods:placeTerm>
    </mods:place>
    <mods:place>
      <mods:placeTerm type='text'>Toronto</mods:placeTerm>
    </mods:place>
  </mods:originInfo>
  <mods:language>
    <mods:languageTerm authority='iso639-2b' type='code'>eng</mods:languageTerm>
  </mods:language>
  <mods:abstract>Daily crawl of YFile</mods:abstract>
  <mods:identifier type='local'>YFILE_$DATE</mods:identifier>
  <mods:physicalDescription>
    <mods:form authority='marcform'>electronic</mods:form>
    <mods:extent>$FILESIZE</mods:extent>
  </mods:physicalDescription>
  <mods:subject>
    <mods:topic>newsletter</mods:topic>
    <mods:topic>York University</mods:topic>
  </mods:subject>
</mods:mods>"

xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltopdf --use-xserver --dpi 200  --page-size Letter http://yfile.news.yorku.ca/ YFILE_$DATE.pdf
xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltoimage --use-xserver http://yfile.news.yorku.ca/ temp.png
pngcrush temp.png YFILE_$DATE.png
rm temp.png
/usr/local/bin/wget --mirror --page-requisites --warc-file=YFILE_$DATE --no-warc-compression --wait=1 http://yfile.news.yorku.ca/
echo $MODS > YFILE_$DATE.xml
cp YFILE_$DATE.warc /mnt/big_data/web-archiving/wayback-warcs
cd /mnt/big_data/web-archiving/warcs
/usr/bin/zip -r YFILE_$DATE.zip YFILE_$DATE
rm -rf YFILE_$DATE
echo "$(date) - YFile archived" >> /var/log/webarchiving.log
