#!/bin/bash
# Bash script that archives selected York University web sites using the WARC ISO format.
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DATE=`date +"%Y_%m_%d"`

cd /mnt/warcs
mkdir YFILE_$DATE
cd YFILE_$DATE

xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltopdf --use-xserver --dpi 200  --page-size Letter http://yfile.news.yorku.ca/ YFILE_$DATE.pdf
xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltoimage --use-xserver http://yfile.news.yorku.ca/ temp.png
pngcrush temp.png YFILE_$DATE.png
rm temp.png
/usr/local/bin/wget --mirror --convert-links --page-requisites --warc-file=YFILE_$DATE --no-warc-compression --wait=3 http://yfile.news.yorku.ca/
cp YFILE_$DATE.warc /home/nruest/tmp/warcs
cd ..
/usr/bin/python /usr/local/bin/bagit.py --processes 4 --contact-name 'Nick Ruest' --contact-email 'ruestn@yorku.ca' --source-organization 'York University' --organization-address '4700 Keele Street Toronto, Ontario M3J 1P3 Canada' --contact-phone '+1 (416)736-2100 x 33235' --external-description 'YFile daily web archive' YFILE_$DATE
zip -r YFILE_$DATE.zip YFILE_$DATE
rm -rf YFILE_$DATE
echo "S'up Dawg? I archived yo yfile site: $(date)" >> /var/log/webarchiving.log
