#!/bin/bash
# Bash script that archives selected York University web sites using the WARC ISO format.
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DATE=`date +"%Y_%m_%d"`

cd /mnt/DIY/web-archiving/warc
mkdir YU_Calendars_$DATE
cd YU_Calendars_$DATE

xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltopdf --use-xserver --dpi 200  --page-size Letter http://calendars.registrar.yorku.ca YU_Calendars_$DATE.pdf
xvfb-run -a -s "-screen 0 1280x1024x24" wkhtmltoimage --use-xserver http://calendars.registrar.yorku.ca temp.png
pngcrush temp.png YU_Calendars_$DATE.png
rm temp.png
/usr/local/bin/wget --mirror --page-requisites --warc-file=YU_Calendars_$DATE --no-warc-compression --wait=1 http://calendars.registrar.yorku.ca
cp YU_Calendars_$DATE.warc /mnt/big_data/web-archiving/wayback-warcs
cd /mnt/DIY/web-archiving/warc
/usr/bin/zip -r YU_Calendars_$DATE.zip YU_Calendars_$DATE
rm -rf YU_Calendars_$DATE
echo "S'up Dawg? I archived yo calendar site: $(date)" >> /var/log/webarchiving.log
