#!/bin/bash
# Bash script that archives selected York University web sites using the WARC ISO format.

cd /media/DIY/DIY/warc-testing
mkdir YU_Calendars_$(date +\%Y_\%m_\%d)
cd YU_Calendars_$(date +\%Y_\%m_\%d)
wget --mirror --warc-file=YU_Calendars_$(date +\%Y_\%m_\%d) http://calendars.registrar.yorku.ca
cd ..
bagit.py --processes 4 --contact-name 'Nick Ruest' --external-description 'York University Calendars (Office of the Registrar) web archive' YU_Calendars_$(date +\%Y_\%m_\%d)
zip -r YU_Calendars_$(date +\%Y_\%m_\%d).zip YU_Calendars_$(date +\%Y_\%m_\%d)
rm -rf YU_Calendars_$(date +\%Y_\%m_\%d)
