#!/bin/bash

DATE=$(date +"%Y_%m_%d")
URL="https://omega.library.yorku.ca:8983/engine/job/secretariat"
LOG_FILE="/var/log/heritrix/secretariat.log"

source credentials.env

function start_crawl {
    local action="$1"
    /usr/bin/curl --silent -d "action=$action" -k -u "$USERNAME:$PASSWORD" --anyauth --location "$URL"
    if [ $? -eq 0 ]; then
        echo "[INFO] $(date) - $action started" >> "$LOG_FILE"
    else
        echo "[ERROR] $(date) - $action" >> "$LOG_FILE"
    fi
}

start_crawl "teardown"
sleep 10
start_crawl "build"
sleep 10
start_crawl "launch"
sleep 10
start_crawl "unpause"
