#!/bin/bash
HOME=/home/nruest/tmp/yu-calendars

cd $HOME

unzip "*.zip"

find $HOME -type f -name "YU_Calendars*warc.gz" -exec cp {} /home/nruest/tmp/yu-calendars-batch \;
find $HOME -type f -name "YU_Calendars*.png" -exec cp {} /home/nruest/tmp/yu-calendars-batch \;
find $HOME -type f -name "YU_Calendars*.pdf" -exec cp {} /home/nruest/tmp/yu-calendars-batch \;

cd /home/nruest/tmp/yu-calendars-batch
gunzip *.gz

cd /home/nruest/tmp/yu-calendars-batch
for i in `ls -1 *.warc`;
    do
        FILESIZE=`ls -sh $i | awk '{print $1}'`
        DATE=`echo $i | sed 'sed -re 's/(YU_Calendars_)(.{4,})(_)(.{2,})(_)(.{2,})(.warc)/\2\-\4\-\6/'`
        FILENAME=`echo $i | sed 's/.warc//'`
        MODS="
<mods:mods xmlns='http://www.loc.gov/mods/v3' xmlns:mods='http://www.loc.gov/mods/v3' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <mods:titleInfo>
    <mods:title>Academic Calendars - $DATE</mods:title>
  </mods:titleInfo>
  <mods:name type='corporate'>
    <mods:namePart>York University Registrat's Office</mods:namePart>
    <mods:role>
      <mods:roleTerm authority='marcrelator' type='text'>Creator</mods:roleTerm>
    </mods:role>
  </mods:name>
  <mods:typeOfResource>mixed material</mods:typeOfResource>
  <mods:genre authority='lctgm'>Website</mods:genre>
  <mods:originInfo>
    <mods:dateIssued>$DATE</mods:dateIssued>
    <mods:publisher>York University</mods:publisher>
    <mods:place>
      <mods:placeTerm authority='marccountry' type='code'>Canada</mods:placeTerm>
    </mods:place>
    <mods:place>
      <mods:placeTerm type='text'>Toronto</mods:placeTerm>
    </mods:place>
  </mods:originInfo>
  <mods:language>
    <mods:languageTerm authority='iso639-2b' type='code'>eng</mods:languageTerm>
  </mods:language>
  <mods:abstract>Bi-monthly crawl of York University Calendars</mods:abstract>
  <mods:identifier type='local'>$FILENAME</mods:identifier>
  <mods:physicalDescription>
    <mods:form authority='marcform'>electronic</mods:form>
    <mods:extent>$FILESIZE</mods:extent>
  </mods:physicalDescription>
  <mods:note></mods:note>
  <mods:subject>$
    <mods:topic>academic calendars</mods:topic>
    <mods:topic>university calendars</mods:topic>
  </mods:subject>
</mods:mods>"

        echo $MODS > $FILENAME.xml
done

